export const cuisineList = [
  // "American",
  // "BBQ",
  // "Breakfast",
  // "Burgers",
  // "Cafe",
  // "Chinese",
  // "Desserts",
  // "French",
  // "Greek",
  // "Healthy",
  // "Indian",
  // "Italian",
  // "Japanese",
  // "Mexican",
  // "Noodles",
  // "Organic",
  // "Pasta",
  // "Pizza",
  // "Salads",
  // "Seafood",
  // "Spanish",
  // "Steak",
  // "Sushi",
  // "Tacos",
  // "Tapas",
  // "Vegan",
  "Biryani",
  "Butter Chicken",
  "Chaat",
  "Dal",
  "Dosa",
  "Gulab Jamun",
  "Hyderabadi",
  "Idli",
  "Kebabs",
  "Kofta",
  "Mughlai",
  "Pani Puri",
  "Paneer",
  "Paratha",
  "Pav Bhaji",
  "Rogan Josh",
  "Samosa",
  "South Indian",
  "Tandoori",
  "Thali",
  "Vada Pav",
  "Chole Bhature",
  "Hakka Noodles",
  "Kachori",
  "Methi Thepla",
];
